// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQwGn6V0xPbguIVmmTH3JFGjDtv6aFcak',
    appId: '1:618329021113:web:dce83f65f203520228d968',
    messagingSenderId: '618329021113',
    projectId: 'literaland-83c05',
    authDomain: 'literaland-83c05.firebaseapp.com',
    storageBucket: 'literaland-83c05.appspot.com',
    measurementId: 'G-MYHCXFMLYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Ek926JK_ZmHano63BxFNEV-YYeTX9Xc',
    appId: '1:618329021113:android:b1835c99ac4830e028d968',
    messagingSenderId: '618329021113',
    projectId: 'literaland-83c05',
    storageBucket: 'literaland-83c05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXY9ceEPkChUwmwBP1V0YUGmqKyraICzw',
    appId: '1:618329021113:ios:1193c53d7e4bdc7328d968',
    messagingSenderId: '618329021113',
    projectId: 'literaland-83c05',
    storageBucket: 'literaland-83c05.appspot.com',
    iosBundleId: 'com.example.literaland',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXY9ceEPkChUwmwBP1V0YUGmqKyraICzw',
    appId: '1:618329021113:ios:1193c53d7e4bdc7328d968',
    messagingSenderId: '618329021113',
    projectId: 'literaland-83c05',
    storageBucket: 'literaland-83c05.appspot.com',
    iosBundleId: 'com.example.literaland',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQwGn6V0xPbguIVmmTH3JFGjDtv6aFcak',
    appId: '1:618329021113:web:ae59eb378731d8d228d968',
    messagingSenderId: '618329021113',
    projectId: 'literaland-83c05',
    authDomain: 'literaland-83c05.firebaseapp.com',
    storageBucket: 'literaland-83c05.appspot.com',
    measurementId: 'G-MDHX19CCE5',
  );

}